configfile: "config.yaml"

report: "report/home.rst"

def cfg(path_value):
    return path_value.format(data_repo=config["data_repo"])

REGIONS = config["regions"]

SCRIPTS_DIR = "scripts"

REFERENCE_DIR = cfg(config["results"]["reference_dir"])
FEATURES_DIR = cfg(config["results"]["features_dir"])
TRAINING_DIR = cfg(config["results"]["training_dir"])
FINAL_MAPS_DIR = cfg(config["results"]["final_maps_dir"])
FEATURE_GEOTIFFS_DIR = f"{config['data_repo']}/results/feature_geotiffs"

include: "rules/reference.smk"
include: "rules/feature_tables.smk"
include: "rules/training_table.smk"
include: "rules/bayes_io.smk"
include: "rules/final_maps.smk"
include: "rules/feature_exports_geotiff.smk"
include: "rules/ie_map_validation.smk"

rule all:
    input:
        expand(f"{REFERENCE_DIR}/{{region}}/ref_grid.tif", region=REGIONS),
        expand(f"{FEATURES_DIR}/tasa_erosion/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/corales/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/tipo_costa/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/zvh/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/velocidad_del_viento/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/estructuras_costeras/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/spp_invasoras/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/pasto_marino/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/batimetria/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/madmex_uso_suelo/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/manglares/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/movimiento_dunas/{{region}}.parquet", region=REGIONS),
        expand(f"{FEATURES_DIR}/condicion_dunas/{{region}}.parquet", region=REGIONS),
        f"{TRAINING_DIR}/master_features.parquet",
        cfg(config["bayes"]["bn_input_parquet"]),
        cfg(config["bayes"]["bn_input_csv"]),
        f"{TRAINING_DIR}/master_features_with_ie.parquet",
        expand(f"{FINAL_MAPS_DIR}/eicoastal_{{region}}.tif", region=REGIONS),
        
