project:
  type: website
  resources:
    - "recursos_externos/"
    
bibliography: docs/referencias.bib   

website:
  title: "Workflow IIE-3T"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
#  sidebar:
  page-navigation: true

format:
  html:
    embed-resources: true
    theme:
      light: cosmo
      dark: darkly
#    css: styles.css
    toc: true
    lang: es
